spring:
  application:
    # 应用程序的名称必须直接映射到Spring Cloud配置服务器中的config目录的名称
    name: licensingservice
  profiles:
    active: default
  config:
    # 指定Spring Cloud Config服务器的位置
    import: "optional:configserver:http://configurationservice:8888"
  cloud:
    stream:
      bindings:
        # input是通道名称，映射到代码中@StreamListener注解属性值
        #input:
        #  destination: org_change_topic
        #  content-type: application/json
        #  group: licensingGroup
        # inboundOrgChanges是通道名称，映射到代码中@StreamListener注解属性值
        inboundOrgChanges:
          destination: org_change_topic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
          # 副本因子，默认为-1，必须设置值
          replication-factor: 1
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    # 注册服务的IP而不是服务名称
    prefer-ip-address: true
  client:
    # 向Eureka注册服务
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # Eureka服务的位置
      defaultZone: http://eurekaservice:8761/eureka/
security:
  oauth2:
    resource:
      userInfoUri: http://authenticationservice:8901/auth/user